[versions]
agp = "8.7.0"
androidbrowserhelper = "2.5.0"
core-ktx = "1.13.1"
kotlin = "2.0.20"

[libraries]
androidbrowserhelper = { module = "com.google.androidbrowserhelper:androidbrowserhelper", version.ref = "androidbrowserhelper" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }